### ISSUE TITLE
Support UUID

### ISSUE THREAD

**Issue by G3z** [umbrellio/laravel-ltree#27]
**Is your feature request related to a problem? Please describe.**
UUID are not supported

**Describe the solution you'd like**
To Use uuid in an ltree a transform to replace "-" with "_" is needed, i think the interface could implement an overridable `getKey` or the helper could check (and clean) if the model is using a string type primary

**Comment by pvsaintpe** [comment]
Hi, Giacomo Trezzi,

Your model uses column with UUID type as a Primary Key? if so, then maybe there will be problems with this.

I think, it might make sense to not get tied to the`QueuebleInterface` interface from `Eloquent\Model`. 

I'll think, what can be done with this and in the near time I think 5-7 days, I'll solve your problem.

**Comment by pvsaintpe** [comment]
I want to note, that using UUID as `getKey()` to build materialized paths isn't very advisable. 

You'll need to add an `int/string` column as a key to your table.  I use an unique column, it’s more convenient for me.

**Comment by G3z** [comment]
> Your model uses column with UUID type as a Primary Key? if so, then maybe there will be problems with this.

Yes!
I did not consider adding another column to be used as "ltree identifier" (if that name makes sense).
If you think this is the most correct/efficient way I'll implement it that way

**Comment by pvsaintpe** [comment]
Ok, stay tuned. 

Do you have time to wait a week?

PS.  Are you using `Umbrellio\Postgres\UmbrellioPostgresProvider` from the `umbrellio/laravel-pg-extensions` package instead of `Illuminate\Database\DatabaseServiceProvider`?

**Comment by G3z** [comment]
Please take all the time you need,
I did not change the provider, should I have ?

**Comment by pvsaintpe** [comment]
Of course!

Our provider expands the capabilities of the Blueprint builder in migrations, and also solves some problems with custom types in Doctrine.

Please, take the time and familiarize yourself with the opportunities that we provide.
