### ISSUE TITLE
Nullable support

### ISSUE THREAD

**Issue by balda38** [umbrellio/laravel-ltree#39]
Hello!

Can you, please, add nullable support in LtreeHelper (in wrapExpressions function)?
Like:
```
if ($value === null) {
    $expressions[] = sprintf('%s = %s', $column, 'null');
}
```
This is important for me and it's right logic if we want set some field to null after move node or other action with it.

Thx a lot!

**Comment by pvsaintpe** [comment]
@balda38 

I need some time to study your question. Can you wait until December 21?

**Comment by balda38** [comment]
@pvsaintpe 
Course, all you need

**Comment by balda38** [comment]
@pvsaintpe 
Just add, that it's necessary, cause sprintf presents null as empty string.

**Comment by pvsaintpe** [comment]
@balda38

Try using build version 6.0.2.

**Comment by balda38** [comment]
@pvsaintpe
Yeap, it's work fine. Thx!
