### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by Atmden** [umbrellio/laravel-ltree#79]
Настало время сделать поддержку Laravel 10

**Comment by videni** [comment]
@pvsaintpe Please support Laravel 10, it seems it also needs to change the package [umbrellio/laravel-common-objects](https://packagist.org/packages/umbrellio/laravel-common-objects). I can do that for you , if you are busy.

**Comment by jamesrusso** [comment]
I've submitted PRs for both of these here: 

https://github.com/umbrellio/laravel-ltree/pull/80
https://github.com/umbrellio/laravel-common-objects/pull/8

**Comment by pvsaintpe** [comment]
@jamesrusso 

Please don't use minor versions in your merge request just "^2.1" is enough because it will work anyway even when your second merge request is merged.

**Comment by jamesrusso** [comment]
> @jamesrusso 
> 
> Please don't use minor versions in your merge request just "^2.1" is enough because it will work anyway even when your second merge request is merged.

Can you please clarify? I just followed the previous examples with the version bump? All the previous packages just had major.minor in them.
